### ISSUE TITLE
webhook可以通过url传值给后端脚本执行吗

### ISSUE THREAD

**Issue by vrocwang** [soulteary/webhook#12]
### 举例如下：
_不确定我的配置文件是否正确_
**配置文件：**

```
- id: test
  execute-command: "/etc/webhook/scripts/test.sh"
  pass-arguments-to-command:
  - source: string
    name: -e  <通过url获取的env的值>
  trigger-rule:
     match:
        type: regex
        regex: .*
        parameter:
          source: url
          name: env
```

**请求：**

`curl http://127.0.0.1:9000/hooks/test?env=test`

希望当请求以上hook时，执行脚本
`/etc/webhook/scripts/test.sh -e test`
