### ISSUE TITLE
如何直接监听`http://0.0.0.0:9000/{id}`

### ISSUE THREAD

**Issue by ValenW** [soulteary/webhook#16]
配置`URL_PREFIX: ""`时效果
<img width="640" alt="image" src="https://github.com/user-attachments/assets/56135e34-db30-402b-a019-b7a90c76bef2">

期望：
直接监听`http://0.0.0.0:9000/{id}`

完整配置
```yaml
services:
  webhook:
    image: soulteary/webhook
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      HOST: "0.0.0.0"
      PORT: 9000
      VERBOSE: true
      HOOKS: "/app/hooks.json"
      DEBUG: true
      URL_PREFIX: ""
      LANGUAGE: zh-CN
      TEMPLATE: true
      # HOT_RELOAD: true
      # NO_PANIC: false
      # LOG_PATH: ""
      # HTTP_METHODS: ""
      # X_REQUEST_ID: false
    env_file:
      - ../.env
    volumes:
      - ./trigger.sh:/app/trigger.sh
      - ./hooks.json:/app/hooks.json
      - ./scripts:/app/scripts
```
